### ISSUE TITLE
Fails when missing a COPY layer

### ISSUE THREAD

**Issue by SamJUK** [duaraghav8/dockershrink#3]
Optimize fails if the target Dockerfile does not include a COPY layer. 

```
Error: Failed to optimize the project: Traceback (most recent call last):
  File "/Users/sam/Personal/sandbox/dockershrink/dockershrink/cli.py", line 161, in optimize_command
    response = project.optimize_docker_image(ai_service)
  File "/Users/sam/Personal/sandbox/dockershrink/dockershrink/project/project.py", line 493, in optimize_docker_image
    self._dockerfile_use_depcheck()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/sam/Personal/sandbox/dockershrink/dockershrink/project/project.py", line 247, in _dockerfile_use_depcheck
    depcheck_layer: df.RunLayer = self.dockerfile.insert_after_layer(
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        last_copy_layer, "RUN npx depcheck"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/sam/Personal/sandbox/dockershrink/dockershrink/dockerfile/dockerfile.py", line 326, in insert_after_layer
    stage = layer.parent_stage()
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parent_stage'
```

**Comment by duaraghav8** [comment]
Can you share your Dockerfile? Or a small snippet I can reproduce this over?

**Comment by SamJUK** [comment]
A stripped down example, would be something like this

```Dockerfile
FROM alpine

WORKDIR /application

RUN apk update
RUN apk add rsync git make curl libzip-dev tar openssh patch bash jq

ENTRYPOINT ["/bin/sh"]
```

**Comment by duaraghav8** [comment]
https://github.com/duaraghav8/dockershrink/commit/9ecd32e7df04c6c7e0a913bce203ac41bbdda6dc
Fix for this is merged and will be out with next release

**Comment by duaraghav8** [comment]
0.1.4 is now released
